- name: Back up configs to folder
  hosts: csrs
  gather_facts: no

  tasks:

  - name: show running-config (IOS)
    when: ansible_network_os == 'ios'
    ios_command:
      commands: show running-config
    register: config

  - name: ensure device folder is created
    file:
      path: "backup/{{ inventory_hostname }}"
      state: directory

  - name: get timestamp
    command: date +%Y%m%d
    register: timestamp

  - copy:
      content: "{{ config.stdout[0] }}"
      dest: "backup/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}.cfg"


